// src/views/Encounter.vue
<template>
  <div class="status-container">
    <div class="status">
      <div class="status-duration" :class="active && 'active'">
        <span>{{ duration }}</span>
      </div>
      <div class="status-content">
        <div class="zone">
          <span>{{ zoneName }}</span>
        </div>
        <div class="numbers">
          <span>{{ totalDPS }}</span>
          <span class="counter">DPS</span>
        </div>
      </div>
      <div class="status-buttons">
        <div class="buttons-end" @click="handleClearOverlay">
          <IRefresh color="#ffffff" />
        </div>
        <div class="buttons-settings" @click="updateShowSettings">
          <ISetting color="#ffffff" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
// deps
import { OverlayAPI } from 'ffxiv-overlay-api';
import { computed } from 'vue';
import { logInfo } from '../utils/loggers.js';
// hooks
import useCombatData from '../hooks/useCombatData.js';
import useSettings from '../hooks/useSettings.js';
// icons
import IRefresh from '../assets/svgs/IRefresh.vue';
import ISetting from '../assets/svgs/ISetting.vue';

/**
 * encounter bar
 * @param {OverlayAPI} overlay overlay instance
 */
export default {
  name: 'Encounter',
  props: {
    overlay: {
      type: OverlayAPI,
      required: true,
    },
  },
  setup(props) {
    // active status
    const { active } = useCombatData();

    // encounter datas
    const { encounter, updateCombatData } = useCombatData();
    const duration = computed(() => encounter.value?.duration || '00:00');
    const zoneName = computed(() => encounter.value?.zoneName || 'Skyline Overlay');
    const totalDPS = computed(() => encounter.value?.dps || 0);

    /**
     * clear overlay data
     */
    const handleClearOverlay = () => {
      logInfo('overlay cleared');
      typeof props.overlay.endEncounter === 'function' && props.overlay.endEncounter();
      updateCombatData({});
    };

    // control settings
    const { updateShowSettings } = useSettings();

    return {
      active,
      duration,
      zoneName,
      totalDPS,
      handleClearOverlay,
      updateShowSettings,
      // icons
      IRefresh,
      ISetting,
    };
  },
};
</script>

<style lang="scss" src="./Encounter.scss">
</style>

// src/views/Encounter.jsx
import React, { useCallback } from 'react';
import cn from 'classnames';
import { observer } from 'mobx-react-lite';
import './Encounter.scss';
import { version } from '@/assets/version';
import { IRefresh, ISettings } from '@/assets/icons';
import { logInfo } from '@/utils/loggers';
import useStore from '@/hooks/useStore';

const Encounter = observer(() => {
  const { api, settings } = useStore();
  const { active, encounter, overlay } = api;

  // encounter data
  const duration = encounter.duration || '00:00';
  const zoneName = encounter.zoneName || `Skyline Overlay ${version}`;
  const totalDPS = encounter.dps || 0;

  /**
   * reset all combat data
   */
  const handleReset = useCallback(() => {
    overlay.endEncounter();
    api.clearCombat();
    logInfo('overlay cleared');
  }, [api, overlay]);

  return (
    <div className='encounter'>
      <div className={cn('encounter-duration', { active })}>
        <span>{duration}</span>
      </div>
      <div className='encounter-content'>
        <div className='encounter-zone'>
          <span>{zoneName}</span>
        </div>
        <div className='encounter-numbers'>
          <span className='s-number'>{totalDPS}</span>
          <span className='s-counter'>DPS</span>
        </div>
      </div>
      <div className='encounter-buttons'>
        <div className='btn' onClick={handleReset}>
          <IRefresh />
        </div>
        <div className='btn' onClick={() => settings.toggleSettings()}>
          <ISettings />
        </div>
      </div>
    </div>
  );
});

export default Encounter;
