// src/App.jsx
import React, { useEffect, useState } from 'react';
import { observer } from 'mobx-react-lite';
import OverlayAPI from 'ffxiv-overlay-api';

import { Combatant, Encounter, Settings } from './views';
import useStore from './hooks/useStore';
import { logInfo } from './utils/loggers';
import { isDev } from './utils/env';

function App() {
  const { combat } = useStore();

  // init overlay api
  const [overlay] = useState(
    () =>
      new OverlayAPI({
        extendData: true,
        silentMode: true,
      })
  );
  useEffect(() => {
    overlay.addListener('CombatData', (obj) => {
      combat.updateCombat(obj.extendData);
    });
    overlay.startEvent();
    logInfo('api initialized');

    // debug mock data
    isDev() &&
      fetch('https://cdn.jsdelivr.net/gh/dsrkafuu/ffxiv-overlay-api@3/test/fake_cn.json')
        .then((res) => res.json())
        .then((obj) => {
          let time = 1;
          const int = setInterval(() => {
            obj.Encounter.duration = `00:${time < 10 ? '0' : ''}${time}`;
            obj.Encounter.encdps = 0;
            Object.keys(obj.Combatant).forEach((idx) => {
              const dps = (Math.random() * 20000).toFixed(0);
              obj.Combatant[idx].encdps = dps;
              obj.Encounter.encdps += Number(dps);
            });
            obj.Encounter.encdps = `${obj.Encounter.encdps}`;
            obj.Combatant['YOU'].name = obj.Combatant['光之战士一号'];
            obj.Combatant['YOU'].name = 'YOU';
            delete obj.Combatant['光之战士一号'];
            overlay.simulateData(obj);
            time++;
          }, 1000);
          setTimeout(() => clearInterval(int), 10 * 1000 + 500);
        });
  }, [combat, overlay]);

  return (
    <>
      <div className='s-container'>
        <Combatant />
      </div>
      <div className='s-container'>
        <Encounter overlay={overlay} />
      </div>
      <div className='s-container'>
        <Settings />
      </div>
    </>
  );
}

export default observer(App);

// src/App.vue
<template>
  <Combatant :combatant="combatant" />
  <Encounter :encounter="encounter" :active="active === 'true' ? true : false" />
</template>

<script>
import OverlayAPI from 'ffxiv-overlay-api';
import { reactive, computed, onMounted, unref } from 'vue';
import { useStore } from 'vuex';
/* mutations */
import { UPDATE_COMBAT_DATA } from './store/mutations.js';
/* components */
import Combatant from './views/Combatant.vue';
import Encounter from './views/Encounter.vue';

export default {
  name: 'App',
  components: {
    Combatant,
    Encounter,
  },
  setup() {
    /* all data */
    const { combatant, encounter, active, updateCombatData } = useCombatData();

    /* init overlay api and start polling data */
    const { overlay } = useOverlayAPI(updateCombatData);
    onMounted(() => {
      overlay.startEvent();
    });

    return {
      combatant,
      encounter,
      active,
    };
  },
};

function useCombatData() {
  const store = useStore();
  // get combat data
  const dataObj = {};
  ['combatant', 'encounter'].forEach((key) => {
    dataObj[key] = computed(() => {
      if (store.state.combatData.type) {
        return store.state.combatData.extendData[key];
      }
      return null;
    });
  });
  const active = computed(() => store.state.combatData.isActive || 'false');
  // update function
  const updateCombatData = (combatData) => {
    store.commit(UPDATE_COMBAT_DATA, combatData);
  };
  return {
    ...dataObj, // a plain object which has two ref that we can split
    active,
    updateCombatData,
  };
}

function useOverlayAPI(updateCombatData) {
  const overlay = new OverlayAPI({
    extendData: true,
    silentMode: process.env.NODE_ENV === 'production',
  });
  overlay.addListener('CombatData', (data) => {
    updateCombatData(data);
  });
  /* DEV - START */
  process.env.NODE_ENV === 'development' &&
    fetch('https://raw.githubusercontent.com/amzrk2/ffxiv-overlay-api/master/test/fake_cn.json')
      .then((response) => {
        return response.json();
      })
      .then((fakeData) => {
        overlay.simulateData(fakeData);
        setTimeout(() => {
          // Disable simulation
          overlay.simulateData();
        }, 10000);
      });
  /* DEV - END */
  return { overlay };
}
</script>
